INSERT INTO PLANT (PLANT_ID, PLANT_NAME) VALUES (1, '첫번째');
INSERT INTO PLANT (PLANT_ID, PLANT_NAME) VALUES (2, '두번째');

INSERT INTO PLANT_INFO (PLANT_ID, IMAGE, DATE, LIGHT_THRESHOLD, SOIL_THRESHOLD, SUNLIGHT_DURATION, GROW_LIGHT_DURATION) VALUES (1, '1.png', '2024-04-01', 40.0, 30.0, 0, 0);
INSERT INTO PLANT_INFO (PLANT_ID, IMAGE, DATE, LIGHT_THRESHOLD, SOIL_THRESHOLD, SUNLIGHT_DURATION, GROW_LIGHT_DURATION) VALUES (2, '2.png', '2024-04-05', 30.0, 20.0, 0, 0);