INSERT INTO PLANT (PLANT_ID, PLANT_NAME) VALUES (1, '첫번째');
INSERT INTO PLANT (PLANT_ID, PLANT_NAME) VALUES (2, '두번째');

INSERT INTO PLANT_INFO (PLANT_ID, IMAGE, DATE) VALUES (1, '1.png', '2024-04-01');
INSERT INTO PLANT_INFO (PLANT_ID, IMAGE, DATE) VALUES (2, '2.png', '2024-04-05');